import { useState, useMemo } from "react";
import { PreValidatedIdea, PreValidatedFilters, PreValidatedSortOption } from "@/types/prevalidated";

// Pre-validated Canadian business ideas database
// Each idea represents 50+ hours of market research
const PRE_VALIDATED_IDEAS: PreValidatedIdea[] = [
  {
    id: "pv-1",
    name: "AI-Powered Bookkeeping for Small Businesses",
    description: "Automated bookkeeping service using AI to categorize expenses, generate reports, and prepare CRA-compliant tax documents for Canadian small businesses. Target solopreneurs and micro-businesses who can't afford traditional accountants.",
    industry: "Finance & Insurance",
    marketSize: "$2.4B CAD (Canadian SMB accounting market)",
    competitorCount: 12,
    topCompetitors: ["Wave", "FreshBooks", "QuickBooks", "Xero"],
    startupCostMin: 5000,
    startupCostMax: 15000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 25000,
    viabilityScore: 88,
    recessionResistanceScore: 92,
    painPointSeverity: 9,
    aiLeverageScore: 95,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Canada Digital Adoption Program", "IRAP", "Ontario Digital Main Street"],
    regulatoryNotes: ["No CPA required for bookkeeping (only for audits)", "Must comply with PIPEDA for data handling", "Consider professional liability insurance"],
    redditMentions: 847,
    searchVolume: "12,100/mo",
    growthTrend: "rising",
    researchHours: 54,
    addedDate: "2025-12-01",
    lastUpdated: "2025-12-28",
    featured: true,
  },
  {
    id: "pv-2",
    name: "Senior Home Tech Setup & Support",
    description: "On-demand tech support service specifically for seniors - setting up smart home devices, teaching video calling, troubleshooting tablets/phones, and ongoing tech support subscriptions. Canada's aging population creates massive demand.",
    industry: "Technology",
    marketSize: "$890M CAD (senior tech services)",
    competitorCount: 5,
    topCompetitors: ["Best Buy Geek Squad", "Local computer shops"],
    startupCostMin: 2000,
    startupCostMax: 8000,
    monthlyRevenueMin: 4000,
    monthlyRevenueMax: 15000,
    viabilityScore: 85,
    recessionResistanceScore: 88,
    painPointSeverity: 8,
    aiLeverageScore: 45,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Quebec", "Alberta"],
    relevantGrants: ["Canada Summer Jobs (if hiring youth)", "CEBA successor programs"],
    regulatoryNotes: ["Police background check recommended", "Consider bonding insurance for in-home visits"],
    redditMentions: 423,
    searchVolume: "6,600/mo",
    growthTrend: "rising",
    researchHours: 48,
    addedDate: "2025-11-15",
    lastUpdated: "2025-12-20",
    featured: true,
  },
  {
    id: "pv-3",
    name: "Electric Vehicle Charging Station Installation",
    description: "Residential and commercial EV charger installation service. With Canada's EV rebates and charging infrastructure push, demand is exploding. Partner with certified electricians or get certification yourself.",
    industry: "Automotive",
    marketSize: "$1.2B CAD (EV infrastructure, growing 40% annually)",
    competitorCount: 8,
    topCompetitors: ["ChargePoint installers", "Tesla certified installers", "Local electricians"],
    startupCostMin: 15000,
    startupCostMax: 50000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 40000,
    viabilityScore: 91,
    recessionResistanceScore: 75,
    painPointSeverity: 8,
    aiLeverageScore: 35,
    newcomerFriendly: false,
    sideHustleCompatible: false,
    bestProvinces: ["British Columbia", "Quebec", "Ontario"],
    relevantGrants: ["NRCan Zero Emission Vehicle Infrastructure Program", "Provincial EV incentives", "Canada Greener Homes"],
    regulatoryNotes: ["Requires electrical contractor license", "Must follow ESA regulations (Ontario)", "Provincial electrical codes vary"],
    redditMentions: 1243,
    searchVolume: "18,100/mo",
    growthTrend: "rising",
    researchHours: 62,
    addedDate: "2025-10-20",
    lastUpdated: "2025-12-25",
    featured: true,
  },
  {
    id: "pv-4",
    name: "Virtual Mental Health Support Coordinator",
    description: "Help Canadians navigate the mental health system - finding therapists, booking appointments, managing waitlists, and coordinating care. Not providing therapy, but administrative support for those seeking help.",
    industry: "Health & Wellness",
    marketSize: "$4.5B CAD (mental health services market)",
    competitorCount: 3,
    topCompetitors: ["Direct therapy services", "Employee assistance programs"],
    startupCostMin: 3000,
    startupCostMax: 10000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 20000,
    viabilityScore: 82,
    recessionResistanceScore: 85,
    painPointSeverity: 10,
    aiLeverageScore: 60,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Women Entrepreneurship Fund"],
    regulatoryNotes: ["Not providing therapy - no license required", "PIPEDA compliance for health info", "Consider professional liability insurance"],
    redditMentions: 2156,
    searchVolume: "9,900/mo",
    growthTrend: "rising",
    researchHours: 51,
    addedDate: "2025-11-01",
    lastUpdated: "2025-12-22",
    featured: false,
  },
  {
    id: "pv-5",
    name: "Subscription Meal Prep for Dietary Restrictions",
    description: "Meal prep service specializing in specific dietary needs - halal, kosher, keto, vegan, allergen-free. Target specific communities with prepared meals delivered weekly. Low competition in niche dietary segments.",
    industry: "Food & Beverage",
    marketSize: "$1.8B CAD (meal kit/prep market)",
    competitorCount: 6,
    topCompetitors: ["HelloFresh", "Goodfood", "Cook It"],
    startupCostMin: 10000,
    startupCostMax: 35000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 30000,
    viabilityScore: 79,
    recessionResistanceScore: 65,
    painPointSeverity: 7,
    aiLeverageScore: 40,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Futurpreneur", "BDC Small Business Loan", "Regional development grants"],
    regulatoryNotes: ["Food handling certification required", "Provincial health inspections", "Commercial kitchen requirements", "Labeling regulations (CFIA)"],
    redditMentions: 567,
    searchVolume: "8,100/mo",
    growthTrend: "stable",
    researchHours: 47,
    addedDate: "2025-09-15",
    lastUpdated: "2025-12-18",
    featured: false,
  },
  {
    id: "pv-6",
    name: "AI Content Creation Agency for Local Businesses",
    description: "Done-for-you content creation using AI tools - social media posts, blog articles, email newsletters, and marketing copy for local Canadian businesses who don't have time or expertise to do it themselves.",
    industry: "Creative Services",
    marketSize: "$3.2B CAD (content marketing services)",
    competitorCount: 15,
    topCompetitors: ["Freelance marketplaces", "Traditional agencies", "In-house teams"],
    startupCostMin: 2000,
    startupCostMax: 8000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 25000,
    viabilityScore: 84,
    recessionResistanceScore: 70,
    painPointSeverity: 8,
    aiLeverageScore: 98,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Digital Adoption Program", "Ontario Digital Main Street"],
    regulatoryNotes: ["CASL compliance for email marketing", "Copyright considerations for AI content", "Business liability insurance recommended"],
    redditMentions: 1834,
    searchVolume: "14,800/mo",
    growthTrend: "rising",
    researchHours: 45,
    addedDate: "2025-12-10",
    lastUpdated: "2025-12-30",
    featured: true,
  },
  {
    id: "pv-7",
    name: "Newcomer Settlement Consulting",
    description: "Help new immigrants navigate Canadian systems - finding housing, opening bank accounts, understanding healthcare, credential recognition, and job searching. Package services for specific communities (Indian, Filipino, Chinese, etc.).",
    industry: "Professional Services",
    marketSize: "$650M CAD (settlement services)",
    competitorCount: 4,
    topCompetitors: ["Government settlement agencies", "Immigration lawyers (different service)"],
    startupCostMin: 3000,
    startupCostMax: 12000,
    monthlyRevenueMin: 4000,
    monthlyRevenueMax: 18000,
    viabilityScore: 86,
    recessionResistanceScore: 90,
    painPointSeverity: 9,
    aiLeverageScore: 55,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "IRCC Settlement funding (if partnering)"],
    regulatoryNotes: ["Cannot provide immigration legal advice without RCIC license", "Focus on settlement, not immigration applications", "Multilingual capability valuable"],
    redditMentions: 678,
    searchVolume: "5,400/mo",
    growthTrend: "rising",
    researchHours: 52,
    addedDate: "2025-10-01",
    lastUpdated: "2025-12-24",
    featured: false,
  },
  {
    id: "pv-8",
    name: "Property Management Tech Platform",
    description: "SaaS platform for small landlords (1-10 units) to manage tenants, collect rent, handle maintenance requests, and stay compliant with provincial tenancy laws. White-label for property managers.",
    industry: "Real Estate",
    marketSize: "$890M CAD (property management software)",
    competitorCount: 8,
    topCompetitors: ["Buildium", "AppFolio", "Rent Manager"],
    startupCostMin: 25000,
    startupCostMax: 75000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 50000,
    viabilityScore: 80,
    recessionResistanceScore: 82,
    painPointSeverity: 8,
    aiLeverageScore: 75,
    newcomerFriendly: false,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["IRAP", "SR&ED Tax Credit", "BDC Innovation loans"],
    regulatoryNotes: ["Must handle provincial tenancy law differences", "Trust accounting requirements", "PIPEDA compliance for tenant data"],
    redditMentions: 956,
    searchVolume: "7,200/mo",
    growthTrend: "stable",
    researchHours: 58,
    addedDate: "2025-08-20",
    lastUpdated: "2025-12-15",
    featured: false,
  },
  {
    id: "pv-9",
    name: "Mobile Pet Grooming Van Service",
    description: "Bring grooming to pet owners' homes with a fully-equipped mobile van. Premium pricing for convenience. Focus on busy professionals and seniors who can't easily transport pets.",
    industry: "Pet Services",
    marketSize: "$1.1B CAD (pet grooming market)",
    competitorCount: 7,
    topCompetitors: ["PetSmart Grooming", "Local groomers", "Other mobile services"],
    startupCostMin: 35000,
    startupCostMax: 80000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 20000,
    viabilityScore: 77,
    recessionResistanceScore: 72,
    painPointSeverity: 6,
    aiLeverageScore: 25,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Futurpreneur", "BDC Small Business Loan", "Canada Small Business Financing Program"],
    regulatoryNotes: ["Vehicle modification permits", "Water disposal regulations", "Business insurance required", "Some municipalities require groomer certification"],
    redditMentions: 432,
    searchVolume: "4,400/mo",
    growthTrend: "stable",
    researchHours: 43,
    addedDate: "2025-07-10",
    lastUpdated: "2025-12-10",
    featured: false,
  },
  {
    id: "pv-10",
    name: "Corporate Wellness Program Coordinator",
    description: "Design and manage wellness programs for mid-size companies - mental health resources, fitness challenges, nutrition coaching, stress management workshops. Recurring revenue from monthly retainers.",
    industry: "Health & Wellness",
    marketSize: "$2.1B CAD (corporate wellness)",
    competitorCount: 9,
    topCompetitors: ["Virgin Pulse", "Sprout", "League"],
    startupCostMin: 5000,
    startupCostMax: 20000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 35000,
    viabilityScore: 83,
    recessionResistanceScore: 68,
    painPointSeverity: 7,
    aiLeverageScore: 60,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Women Entrepreneurship Fund", "Futurpreneur", "Regional innovation grants"],
    regulatoryNotes: ["Not providing medical advice - no license needed", "Health and safety certifications helpful", "Consider liability insurance"],
    redditMentions: 567,
    searchVolume: "6,100/mo",
    growthTrend: "rising",
    researchHours: 49,
    addedDate: "2025-11-20",
    lastUpdated: "2025-12-26",
    featured: false,
  },
  {
    id: "pv-11",
    name: "Skilled Trades Recruitment Agency",
    description: "Specialized recruitment for electricians, plumbers, HVAC technicians, and other skilled trades. Canada faces severe trades shortage - connect tradespeople with companies willing to pay premium rates.",
    industry: "Professional Services",
    marketSize: "$4.8B CAD (recruitment industry, trades segment growing fastest)",
    competitorCount: 6,
    topCompetitors: ["Indeed", "Workopolis", "General staffing agencies"],
    startupCostMin: 8000,
    startupCostMax: 25000,
    monthlyRevenueMin: 10000,
    monthlyRevenueMax: 50000,
    viabilityScore: 87,
    recessionResistanceScore: 85,
    painPointSeverity: 9,
    aiLeverageScore: 65,
    newcomerFriendly: false,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "Alberta", "British Columbia"],
    relevantGrants: ["Canada Job Grant", "Provincial workforce development funds"],
    regulatoryNotes: ["Employment agency license required in some provinces", "Labour standards compliance", "Background check processes"],
    redditMentions: 1123,
    searchVolume: "9,300/mo",
    growthTrend: "rising",
    researchHours: 55,
    addedDate: "2025-09-01",
    lastUpdated: "2025-12-20",
    featured: true,
  },
  {
    id: "pv-12",
    name: "Eco-Friendly Cleaning Service",
    description: "Residential and commercial cleaning using only eco-certified products. Target environmentally conscious homeowners and businesses with sustainability mandates. Premium pricing for green credentials.",
    industry: "Home Services",
    marketSize: "$6.2B CAD (cleaning services market)",
    competitorCount: 12,
    topCompetitors: ["Molly Maid", "MaidPro", "Local cleaners"],
    startupCostMin: 5000,
    startupCostMax: 15000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 25000,
    viabilityScore: 78,
    recessionResistanceScore: 75,
    painPointSeverity: 6,
    aiLeverageScore: 35,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["British Columbia", "Ontario", "Quebec"],
    relevantGrants: ["Futurpreneur", "Green business grants", "Women entrepreneurship programs"],
    regulatoryNotes: ["WHMIS training required", "Liability insurance essential", "Worker's compensation if hiring employees"],
    redditMentions: 389,
    searchVolume: "5,900/mo",
    growthTrend: "stable",
    researchHours: 41,
    addedDate: "2025-06-15",
    lastUpdated: "2025-12-05",
    featured: false,
  },
  {
    id: "pv-13",
    name: "Cannabis Delivery Service",
    description: "Licensed cannabis delivery in provinces that allow it. Partner with licensed retailers or obtain your own license. Focus on convenience, speed, and age verification compliance.",
    industry: "Cannabis",
    marketSize: "$5.3B CAD (legal cannabis market)",
    competitorCount: 8,
    topCompetitors: ["OCS (Ontario)", "SQDC (Quebec)", "Licensed retailers"],
    startupCostMin: 50000,
    startupCostMax: 150000,
    monthlyRevenueMin: 15000,
    monthlyRevenueMax: 80000,
    viabilityScore: 75,
    recessionResistanceScore: 70,
    painPointSeverity: 6,
    aiLeverageScore: 45,
    newcomerFriendly: false,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "Alberta", "Saskatchewan"],
    relevantGrants: ["Limited - cannabis excluded from most programs", "BDC loans (case by case)"],
    regulatoryNotes: ["Provincial cannabis regulations vary significantly", "Security clearances required", "Strict inventory tracking", "Age verification systems mandatory"],
    redditMentions: 1567,
    searchVolume: "22,200/mo",
    growthTrend: "stable",
    researchHours: 67,
    addedDate: "2025-08-01",
    lastUpdated: "2025-12-12",
    featured: false,
  },
  {
    id: "pv-14",
    name: "Remote Work Tech Setup Consultant",
    description: "Help companies set up remote and hybrid work infrastructure - home office equipment, collaboration tools, security protocols, and productivity systems. Target SMBs transitioning to permanent hybrid.",
    industry: "Technology",
    marketSize: "$1.4B CAD (remote work solutions)",
    competitorCount: 7,
    topCompetitors: ["IT consulting firms", "Microsoft partners", "Managed service providers"],
    startupCostMin: 5000,
    startupCostMax: 20000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 30000,
    viabilityScore: 81,
    recessionResistanceScore: 78,
    painPointSeverity: 7,
    aiLeverageScore: 70,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Digital Adoption Program", "IRAP", "Provincial digital transformation grants"],
    regulatoryNotes: ["Consider IT certifications (CompTIA, Microsoft)", "Cybersecurity knowledge essential", "Professional liability insurance"],
    redditMentions: 892,
    searchVolume: "7,700/mo",
    growthTrend: "stable",
    researchHours: 46,
    addedDate: "2025-10-10",
    lastUpdated: "2025-12-22",
    featured: false,
  },
  {
    id: "pv-15",
    name: "Virtual Tutoring Platform for Canadian Curriculum",
    description: "Online tutoring specifically aligned with Canadian provincial curricula. Target K-12 students with subject specialists. Differentiate from generic tutoring with local curriculum expertise.",
    industry: "Education & Training",
    marketSize: "$1.9B CAD (tutoring market)",
    competitorCount: 10,
    topCompetitors: ["Kumon", "Sylvan", "Varsity Tutors", "Wyzant"],
    startupCostMin: 8000,
    startupCostMax: 30000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 25000,
    viabilityScore: 82,
    recessionResistanceScore: 80,
    painPointSeverity: 7,
    aiLeverageScore: 75,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "SR&ED (if building tech)", "Provincial education grants"],
    regulatoryNotes: ["Police background checks for tutors", "PIPEDA for student data", "Consider tutoring association membership"],
    redditMentions: 678,
    searchVolume: "8,900/mo",
    growthTrend: "rising",
    researchHours: 50,
    addedDate: "2025-09-20",
    lastUpdated: "2025-12-18",
    featured: false,
  },
  // ===== NEW IDEAS: Cybersecurity =====
  {
    id: "pv-16",
    name: "SMB Cybersecurity Consulting",
    description: "Help small businesses protect themselves from cyber threats - security audits, employee training, policy development, and incident response planning. Most SMBs are vulnerable but don't know where to start.",
    industry: "Cybersecurity",
    marketSize: "$2.8B CAD (Canadian cybersecurity market)",
    competitorCount: 6,
    topCompetitors: ["Big IT firms", "Managed service providers", "Enterprise security companies"],
    startupCostMin: 5000,
    startupCostMax: 20000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 40000,
    viabilityScore: 89,
    recessionResistanceScore: 88,
    painPointSeverity: 9,
    aiLeverageScore: 70,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["IRAP", "Canada Digital Adoption Program", "SR&ED Tax Credit"],
    regulatoryNotes: ["Security certifications valuable (CISSP, CompTIA Security+)", "PIPEDA compliance expertise needed", "Professional liability insurance essential"],
    redditMentions: 1456,
    searchVolume: "11,200/mo",
    growthTrend: "rising",
    researchHours: 53,
    addedDate: "2025-12-15",
    lastUpdated: "2025-12-30",
    featured: true,
  },
  {
    id: "pv-17",
    name: "PIPEDA Privacy Compliance Services",
    description: "Help Canadian businesses comply with privacy regulations - PIPEDA audits, privacy policy development, breach response planning, and ongoing compliance monitoring. Increasing enforcement makes this essential.",
    industry: "Cybersecurity",
    marketSize: "$450M CAD (privacy compliance services)",
    competitorCount: 4,
    topCompetitors: ["Law firms", "Big 4 consulting", "Enterprise compliance tools"],
    startupCostMin: 3000,
    startupCostMax: 12000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 30000,
    viabilityScore: 85,
    recessionResistanceScore: 90,
    painPointSeverity: 8,
    aiLeverageScore: 65,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Women Entrepreneurship Fund"],
    regulatoryNotes: ["Privacy certification (CIPP/C) valuable", "Stay updated on Bill C-27", "Consider E&O insurance"],
    redditMentions: 567,
    searchVolume: "4,800/mo",
    growthTrend: "rising",
    researchHours: 47,
    addedDate: "2025-12-18",
    lastUpdated: "2025-12-30",
    featured: false,
  },
  // ===== NEW IDEAS: Green Technology =====
  {
    id: "pv-18",
    name: "Home Energy Audit & Retrofit Consulting",
    description: "Help homeowners assess energy efficiency and plan retrofits to qualify for Canada Greener Homes grants. Guide them through the process from audit to rebate collection. Growing demand as energy costs rise.",
    industry: "Green Technology",
    marketSize: "$1.5B CAD (home energy efficiency market)",
    competitorCount: 5,
    topCompetitors: ["Utility company programs", "HVAC contractors", "Energy advisors"],
    startupCostMin: 8000,
    startupCostMax: 25000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 25000,
    viabilityScore: 84,
    recessionResistanceScore: 82,
    painPointSeverity: 7,
    aiLeverageScore: 50,
    newcomerFriendly: false,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Greener Homes", "Provincial energy efficiency grants", "NRCan programs"],
    regulatoryNotes: ["NRCan energy advisor certification required", "EnerGuide rating system training", "Provincial requirements vary"],
    redditMentions: 892,
    searchVolume: "8,900/mo",
    growthTrend: "rising",
    researchHours: 51,
    addedDate: "2025-12-10",
    lastUpdated: "2025-12-28",
    featured: false,
  },
  {
    id: "pv-19",
    name: "E-Waste Recycling & Refurbishment",
    description: "Collect, refurbish, and responsibly recycle electronics. Partner with businesses for bulk pickups. Resell refurbished devices or extract valuable components. Growing regulatory pressure creates opportunity.",
    industry: "Green Technology",
    marketSize: "$780M CAD (e-waste management)",
    competitorCount: 4,
    topCompetitors: ["Municipal programs", "Staples recycling", "Greentec"],
    startupCostMin: 20000,
    startupCostMax: 60000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 35000,
    viabilityScore: 80,
    recessionResistanceScore: 78,
    painPointSeverity: 7,
    aiLeverageScore: 40,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Sustainable Development Technology Canada", "Provincial environmental grants", "Circular economy funds"],
    regulatoryNotes: ["Provincial e-waste regulations", "Environmental permits required", "Data destruction certification valuable", "R2 certification for processors"],
    redditMentions: 456,
    searchVolume: "5,400/mo",
    growthTrend: "rising",
    researchHours: 48,
    addedDate: "2025-11-25",
    lastUpdated: "2025-12-26",
    featured: false,
  },
  // ===== NEW IDEAS: Elder Care =====
  {
    id: "pv-20",
    name: "Senior Companion & Errand Service",
    description: "Non-medical companion services for seniors - conversation, accompaniment to appointments, grocery shopping, light housekeeping, and social activities. Canada's aging population creates massive demand.",
    industry: "Elder Care",
    marketSize: "$3.2B CAD (home care market)",
    competitorCount: 7,
    topCompetitors: ["Bayshore Home Health", "CarePartners", "Local agencies"],
    startupCostMin: 3000,
    startupCostMax: 12000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 20000,
    viabilityScore: 86,
    recessionResistanceScore: 92,
    painPointSeverity: 8,
    aiLeverageScore: 30,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Women Entrepreneurship Fund", "Provincial home care initiatives"],
    regulatoryNotes: ["Police background check required", "First aid certification recommended", "Not providing medical care - no nursing license needed", "Consider bonding insurance"],
    redditMentions: 723,
    searchVolume: "7,200/mo",
    growthTrend: "rising",
    researchHours: 44,
    addedDate: "2025-12-05",
    lastUpdated: "2025-12-28",
    featured: true,
  },
  {
    id: "pv-21",
    name: "Medical Equipment Rental for Seniors",
    description: "Rent mobility aids, hospital beds, lift chairs, and other medical equipment to seniors and families. Short-term rentals for post-surgery recovery or long-term for aging in place.",
    industry: "Elder Care",
    marketSize: "$890M CAD (medical equipment rental)",
    competitorCount: 5,
    topCompetitors: ["Home Depot rental", "Hospital equipment programs", "Medical supply stores"],
    startupCostMin: 25000,
    startupCostMax: 80000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 30000,
    viabilityScore: 81,
    recessionResistanceScore: 88,
    painPointSeverity: 7,
    aiLeverageScore: 45,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["BDC Small Business Loan", "Canada Small Business Financing Program"],
    regulatoryNotes: ["Medical device regulations (Class I exempt for most rentals)", "Sanitization protocols", "Delivery and setup liability", "Consider equipment insurance"],
    redditMentions: 345,
    searchVolume: "4,100/mo",
    growthTrend: "rising",
    researchHours: 46,
    addedDate: "2025-11-20",
    lastUpdated: "2025-12-22",
    featured: false,
  },
  // ===== NEW IDEAS: Subscription Services =====
  {
    id: "pv-22",
    name: "Canadian Artisan Snack Subscription Box",
    description: "Monthly subscription box featuring Canadian-made snacks, treats, and beverages from local artisan producers. Support local while introducing customers to new products. Strong gifting potential.",
    industry: "Subscription Services",
    marketSize: "$1.2B CAD (subscription box market)",
    competitorCount: 6,
    topCompetitors: ["SnackCrate", "Universal Yums", "Generic snack boxes"],
    startupCostMin: 8000,
    startupCostMax: 25000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 30000,
    viabilityScore: 77,
    recessionResistanceScore: 60,
    painPointSeverity: 5,
    aiLeverageScore: 55,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Regional development grants", "Provincial food industry grants"],
    regulatoryNotes: ["CFIA labeling requirements", "Provincial food handling regulations", "Shipping perishables requires care", "Cross-border shipping complex"],
    redditMentions: 567,
    searchVolume: "6,800/mo",
    growthTrend: "stable",
    researchHours: 42,
    addedDate: "2025-10-15",
    lastUpdated: "2025-12-18",
    featured: false,
  },
  {
    id: "pv-23",
    name: "Kids Clothing Rental Subscription",
    description: "Subscription service for children's clothing - parents receive seasonal wardrobes, return when kids outgrow them, get new sizes. Sustainable, cost-effective, and convenient for busy parents.",
    industry: "Subscription Services",
    marketSize: "$340M CAD (kids clothing market segment)",
    competitorCount: 3,
    topCompetitors: ["Thrift stores", "Facebook Marketplace", "Traditional retail"],
    startupCostMin: 15000,
    startupCostMax: 45000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 35000,
    viabilityScore: 79,
    recessionResistanceScore: 72,
    painPointSeverity: 7,
    aiLeverageScore: 50,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Women Entrepreneurship Fund", "Sustainable business grants", "Futurpreneur"],
    regulatoryNotes: ["Consumer protection regulations", "Cleaning/sanitization standards", "Subscription billing regulations", "Returns policy clarity"],
    redditMentions: 423,
    searchVolume: "3,900/mo",
    growthTrend: "rising",
    researchHours: 45,
    addedDate: "2025-11-10",
    lastUpdated: "2025-12-20",
    featured: false,
  },
  // ===== NEW IDEAS: Remote Work =====
  {
    id: "pv-24",
    name: "Virtual Team Building Event Planning",
    description: "Plan and facilitate engaging virtual events for remote teams - trivia nights, escape rooms, cooking classes, wellness sessions. Companies struggle to maintain culture with distributed teams.",
    industry: "Remote Work",
    marketSize: "$420M CAD (team building market)",
    competitorCount: 8,
    topCompetitors: ["Outback Team Building", "TeamBonding", "Local event companies"],
    startupCostMin: 3000,
    startupCostMax: 10000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 25000,
    viabilityScore: 82,
    recessionResistanceScore: 65,
    painPointSeverity: 7,
    aiLeverageScore: 60,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Women Entrepreneurship Fund"],
    regulatoryNotes: ["Event insurance recommended", "Zoom/Teams platform expertise", "AODA accessibility compliance", "Bilingual offering valuable"],
    redditMentions: 567,
    searchVolume: "5,200/mo",
    growthTrend: "stable",
    researchHours: 41,
    addedDate: "2025-12-08",
    lastUpdated: "2025-12-28",
    featured: false,
  },
  {
    id: "pv-25",
    name: "Hybrid Workspace Design Consulting",
    description: "Help companies redesign offices for hybrid work - hot desking layouts, collaboration zones, booking systems, and technology integration. Office renovations happening everywhere post-pandemic.",
    industry: "Remote Work",
    marketSize: "$890M CAD (office design/renovation)",
    competitorCount: 5,
    topCompetitors: ["Architecture firms", "Interior designers", "Furniture dealers"],
    startupCostMin: 8000,
    startupCostMax: 25000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 40000,
    viabilityScore: 80,
    recessionResistanceScore: 60,
    painPointSeverity: 6,
    aiLeverageScore: 55,
    newcomerFriendly: false,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Canada Digital Adoption Program", "Regional development grants"],
    regulatoryNotes: ["Interior design certification helpful in some provinces", "Building code knowledge required", "Accessibility standards (AODA in Ontario)"],
    redditMentions: 345,
    searchVolume: "3,200/mo",
    growthTrend: "stable",
    researchHours: 44,
    addedDate: "2025-11-28",
    lastUpdated: "2025-12-24",
    featured: false,
  },
  // ===== NEW IDEAS: Skilled Trades =====
  {
    id: "pv-26",
    name: "Appliance Repair Service",
    description: "Repair household appliances - washers, dryers, dishwashers, refrigerators. Severe shortage of repair technicians creates opportunity. Right to repair movement growing. Focus on sustainability angle.",
    industry: "Skilled Trades",
    marketSize: "$2.1B CAD (appliance repair market)",
    competitorCount: 4,
    topCompetitors: ["Manufacturer service", "Big box store services", "Local repair shops"],
    startupCostMin: 10000,
    startupCostMax: 30000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 25000,
    viabilityScore: 85,
    recessionResistanceScore: 88,
    painPointSeverity: 8,
    aiLeverageScore: 40,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Canada Small Business Financing Program"],
    regulatoryNotes: ["No license required in most provinces", "Gas appliance repair requires certification", "Consider liability insurance", "Refrigerant handling certification for fridges"],
    redditMentions: 1234,
    searchVolume: "14,500/mo",
    growthTrend: "rising",
    researchHours: 48,
    addedDate: "2025-12-12",
    lastUpdated: "2025-12-30",
    featured: true,
  },
  {
    id: "pv-27",
    name: "Mobile Pressure Washing Business",
    description: "Exterior cleaning for homes and businesses - driveways, siding, decks, patios, commercial parking lots. Low barrier to entry, high demand in spring/summer. Can upsell gutter cleaning and window washing.",
    industry: "Skilled Trades",
    marketSize: "$780M CAD (exterior cleaning services)",
    competitorCount: 6,
    topCompetitors: ["Local operators", "Window cleaning companies", "Landscaping companies"],
    startupCostMin: 5000,
    startupCostMax: 15000,
    monthlyRevenueMin: 5000,
    monthlyRevenueMax: 20000,
    viabilityScore: 78,
    recessionResistanceScore: 65,
    painPointSeverity: 6,
    aiLeverageScore: 25,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Futurpreneur", "Summer Company (Ontario, for youth)"],
    regulatoryNotes: ["Water usage regulations in some municipalities", "Environmental runoff considerations", "Liability insurance essential", "Commercial insurance for business properties"],
    redditMentions: 567,
    searchVolume: "8,100/mo",
    growthTrend: "stable",
    researchHours: 38,
    addedDate: "2025-10-25",
    lastUpdated: "2025-12-15",
    featured: false,
  },
  // ===== NEW IDEAS: Digital Services =====
  {
    id: "pv-28",
    name: "Local SEO Agency for Service Businesses",
    description: "Specialized SEO for local service businesses - plumbers, dentists, lawyers, restaurants. Focus on Google Business Profile optimization, local citations, and review management. High recurring revenue.",
    industry: "Digital Services",
    marketSize: "$1.8B CAD (digital marketing services)",
    competitorCount: 12,
    topCompetitors: ["Generic digital agencies", "Freelancers", "National SEO firms"],
    startupCostMin: 3000,
    startupCostMax: 10000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 30000,
    viabilityScore: 84,
    recessionResistanceScore: 70,
    painPointSeverity: 8,
    aiLeverageScore: 85,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Digital Adoption Program", "Futurpreneur"],
    regulatoryNotes: ["No license required", "Client contracts essential", "Results-based guarantees risky", "Consider E&O insurance"],
    redditMentions: 1567,
    searchVolume: "12,300/mo",
    growthTrend: "rising",
    researchHours: 46,
    addedDate: "2025-12-01",
    lastUpdated: "2025-12-28",
    featured: false,
  },
  {
    id: "pv-29",
    name: "E-commerce Store Setup & Migration",
    description: "Help traditional retailers launch online stores or migrate between platforms (WooCommerce, Shopify, BigCommerce). Include product photography, inventory setup, and payment integration. One-time projects with maintenance upsell.",
    industry: "Digital Services",
    marketSize: "$2.4B CAD (e-commerce services market)",
    competitorCount: 10,
    topCompetitors: ["Shopify Experts", "Freelance developers", "Web agencies"],
    startupCostMin: 5000,
    startupCostMax: 15000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 35000,
    viabilityScore: 82,
    recessionResistanceScore: 68,
    painPointSeverity: 8,
    aiLeverageScore: 75,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Digital Adoption Program", "Ontario Digital Main Street"],
    regulatoryNotes: ["PCI compliance knowledge needed", "Canadian tax (GST/HST) implementation", "CASL for email marketing setup", "Accessibility requirements"],
    redditMentions: 892,
    searchVolume: "9,700/mo",
    growthTrend: "stable",
    researchHours: 49,
    addedDate: "2025-11-15",
    lastUpdated: "2025-12-22",
    featured: false,
  },
  // ===== NEW IDEAS: AI & Automation =====
  {
    id: "pv-30",
    name: "AI Chatbot Implementation for SMBs",
    description: "Deploy and customize AI chatbots for small business websites - customer service, appointment booking, FAQ automation. Use platforms like ChatGPT, Claude, or Intercom. Reduce customer service costs for clients.",
    industry: "AI & Automation",
    marketSize: "$680M CAD (conversational AI market)",
    competitorCount: 7,
    topCompetitors: ["Enterprise chatbot vendors", "Managed service providers", "DIY platforms"],
    startupCostMin: 5000,
    startupCostMax: 20000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 40000,
    viabilityScore: 87,
    recessionResistanceScore: 75,
    painPointSeverity: 8,
    aiLeverageScore: 95,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["IRAP", "Canada Digital Adoption Program", "SR&ED Tax Credit"],
    regulatoryNotes: ["PIPEDA compliance for customer data", "Disclosure requirements for AI", "Accessibility considerations", "Multi-language support for Quebec"],
    redditMentions: 1345,
    searchVolume: "15,600/mo",
    growthTrend: "rising",
    researchHours: 52,
    addedDate: "2025-12-18",
    lastUpdated: "2025-12-30",
    featured: true,
  },
  {
    id: "pv-31",
    name: "Business Process Automation Consulting",
    description: "Help businesses automate repetitive tasks using tools like Zapier, Make, Power Automate, and n8n. Document workflows, implement automations, and train staff. Focus on time and cost savings.",
    industry: "AI & Automation",
    marketSize: "$1.2B CAD (business automation market)",
    competitorCount: 6,
    topCompetitors: ["IT consulting firms", "Implementation partners", "Freelancers"],
    startupCostMin: 3000,
    startupCostMax: 12000,
    monthlyRevenueMin: 7000,
    monthlyRevenueMax: 35000,
    viabilityScore: 85,
    recessionResistanceScore: 80,
    painPointSeverity: 8,
    aiLeverageScore: 90,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Canada Digital Adoption Program", "IRAP", "Futurpreneur"],
    regulatoryNotes: ["Data handling agreements needed", "System integration security", "Documentation for client handoff", "Consider E&O insurance"],
    redditMentions: 789,
    searchVolume: "8,400/mo",
    growthTrend: "rising",
    researchHours: 47,
    addedDate: "2025-12-20",
    lastUpdated: "2025-12-30",
    featured: false,
  },
  // ===== NEW IDEAS: Food Innovation =====
  {
    id: "pv-32",
    name: "Ghost Kitchen Operator",
    description: "Delivery-only restaurant operating from a commercial kitchen. Run multiple virtual brands from one location. Lower overhead than traditional restaurants. Focus on high-margin delivery items.",
    industry: "Food & Beverage",
    marketSize: "$4.2B CAD (food delivery market)",
    competitorCount: 8,
    topCompetitors: ["Traditional restaurants", "Other ghost kitchens", "Meal prep services"],
    startupCostMin: 30000,
    startupCostMax: 100000,
    monthlyRevenueMin: 15000,
    monthlyRevenueMax: 60000,
    viabilityScore: 76,
    recessionResistanceScore: 55,
    painPointSeverity: 6,
    aiLeverageScore: 50,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["BDC Small Business Loan", "Canada Small Business Financing Program", "Regional development grants"],
    regulatoryNotes: ["Commercial kitchen license required", "Health and safety inspections", "Food handler certification", "Delivery platform fees (15-30%)"],
    redditMentions: 1123,
    searchVolume: "9,900/mo",
    growthTrend: "stable",
    researchHours: 54,
    addedDate: "2025-10-05",
    lastUpdated: "2025-12-18",
    featured: false,
  },
  {
    id: "pv-33",
    name: "Specialty Coffee Micro-Roastery",
    description: "Small-batch specialty coffee roasting for local cafes, offices, and direct-to-consumer subscriptions. Focus on quality, origin stories, and sustainability. Growing coffee culture in Canada.",
    industry: "Food & Beverage",
    marketSize: "$2.8B CAD (coffee market)",
    competitorCount: 9,
    topCompetitors: ["National roasters", "Local micro-roasters", "Import brands"],
    startupCostMin: 25000,
    startupCostMax: 75000,
    monthlyRevenueMin: 8000,
    monthlyRevenueMax: 35000,
    viabilityScore: 75,
    recessionResistanceScore: 70,
    painPointSeverity: 5,
    aiLeverageScore: 35,
    newcomerFriendly: true,
    sideHustleCompatible: false,
    bestProvinces: ["British Columbia", "Ontario", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Regional development grants", "Provincial food processing grants"],
    regulatoryNotes: ["Food processing license required", "CFIA labeling requirements", "Commercial kitchen or dedicated space", "Roasting equipment ventilation"],
    redditMentions: 678,
    searchVolume: "7,800/mo",
    growthTrend: "stable",
    researchHours: 48,
    addedDate: "2025-09-28",
    lastUpdated: "2025-12-14",
    featured: false,
  },
  // ===== NEW IDEAS: Niche Markets =====
  {
    id: "pv-34",
    name: "Pet Photography & Social Media Content",
    description: "Professional pet photography combined with social media content creation. Help pet influencer accounts grow or create marketing content for pet businesses. Growing pet parent market.",
    industry: "Pet Services",
    marketSize: "$450M CAD (pet services photography segment)",
    competitorCount: 5,
    topCompetitors: ["General photographers", "Phone photography", "Pet owners DIY"],
    startupCostMin: 5000,
    startupCostMax: 15000,
    monthlyRevenueMin: 4000,
    monthlyRevenueMax: 18000,
    viabilityScore: 74,
    recessionResistanceScore: 55,
    painPointSeverity: 5,
    aiLeverageScore: 60,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta"],
    relevantGrants: ["Futurpreneur", "Arts grants (some apply to photography)"],
    regulatoryNotes: ["Business insurance for working with animals", "Model releases for commercial use", "Copyright ownership clarity", "Indoor studio vs mobile setup"],
    redditMentions: 345,
    searchVolume: "3,600/mo",
    growthTrend: "rising",
    researchHours: 39,
    addedDate: "2025-11-08",
    lastUpdated: "2025-12-20",
    featured: false,
  },
  {
    id: "pv-35",
    name: "Estate Sale & Downsizing Service",
    description: "Help seniors and families organize, price, and sell estate contents. Manage estate sales, donations, and cleanouts. Growing demand as Boomers downsize. Often combined with moving services.",
    industry: "Professional Services",
    marketSize: "$560M CAD (estate services market)",
    competitorCount: 4,
    topCompetitors: ["Auction houses", "Junk removal companies", "Consignment shops"],
    startupCostMin: 5000,
    startupCostMax: 20000,
    monthlyRevenueMin: 6000,
    monthlyRevenueMax: 25000,
    viabilityScore: 82,
    recessionResistanceScore: 85,
    painPointSeverity: 8,
    aiLeverageScore: 45,
    newcomerFriendly: true,
    sideHustleCompatible: true,
    bestProvinces: ["Ontario", "British Columbia", "Alberta", "Quebec"],
    relevantGrants: ["Futurpreneur", "Women Entrepreneurship Fund"],
    regulatoryNotes: ["Bonding recommended for handling valuables", "Knowledge of antiques/collectibles valuable", "Clear contracts for commission structure", "Consider liability insurance"],
    redditMentions: 567,
    searchVolume: "5,100/mo",
    growthTrend: "rising",
    researchHours: 43,
    addedDate: "2025-12-02",
    lastUpdated: "2025-12-26",
    featured: false,
  },
];

const INDUSTRIES = [
  "AI & Automation",
  "Automotive",
  "Cannabis",
  "Cybersecurity",
  "Creative Services",
  "Digital Services",
  "Education & Training",
  "Elder Care",
  "Finance & Insurance",
  "Food & Beverage",
  "Green Technology",
  "Health & Wellness",
  "Home Services",
  "Pet Services",
  "Professional Services",
  "Real Estate",
  "Remote Work",
  "Skilled Trades",
  "Subscription Services",
  "Technology",
];

const PROVINCES = [
  "Ontario",
  "British Columbia",
  "Alberta",
  "Quebec",
  "Saskatchewan",
  "Manitoba",
  "Nova Scotia",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Prince Edward Island",
];

export const usePreValidatedIdeas = () => {
  const [filters, setFilters] = useState<PreValidatedFilters>({
    search: "",
    industry: null,
    province: null,
    sideHustleOnly: false,
    newcomerFriendlyOnly: false,
    minViability: null,
    growthTrend: null,
  });

  const [sortBy, setSortBy] = useState<PreValidatedSortOption>("viability-high");

  const filteredAndSortedIdeas = useMemo(() => {
    let result = [...PRE_VALIDATED_IDEAS];

    // Apply filters
    if (filters.search) {
      const searchLower = filters.search.toLowerCase();
      result = result.filter(
        (idea) =>
          idea.name.toLowerCase().includes(searchLower) ||
          idea.description.toLowerCase().includes(searchLower) ||
          idea.industry.toLowerCase().includes(searchLower)
      );
    }

    if (filters.industry) {
      result = result.filter((idea) => idea.industry === filters.industry);
    }

    if (filters.province) {
      result = result.filter((idea) => idea.bestProvinces.includes(filters.province!));
    }

    if (filters.sideHustleOnly) {
      result = result.filter((idea) => idea.sideHustleCompatible);
    }

    if (filters.newcomerFriendlyOnly) {
      result = result.filter((idea) => idea.newcomerFriendly);
    }

    if (filters.minViability !== null) {
      result = result.filter((idea) => idea.viabilityScore >= filters.minViability!);
    }

    if (filters.growthTrend) {
      result = result.filter((idea) => idea.growthTrend === filters.growthTrend);
    }

    // Apply sorting
    switch (sortBy) {
      case "newest":
        result.sort((a, b) => new Date(b.addedDate).getTime() - new Date(a.addedDate).getTime());
        break;
      case "viability-high":
        result.sort((a, b) => b.viabilityScore - a.viabilityScore);
        break;
      case "viability-low":
        result.sort((a, b) => a.viabilityScore - b.viabilityScore);
        break;
      case "pain-high":
        result.sort((a, b) => b.painPointSeverity - a.painPointSeverity);
        break;
      case "cost-low":
        result.sort((a, b) => a.startupCostMin - b.startupCostMin);
        break;
      case "cost-high":
        result.sort((a, b) => b.startupCostMax - a.startupCostMax);
        break;
      case "recession-high":
        result.sort((a, b) => b.recessionResistanceScore - a.recessionResistanceScore);
        break;
    }

    return result;
  }, [filters, sortBy]);

  const featuredIdeas = useMemo(
    () => PRE_VALIDATED_IDEAS.filter((idea) => idea.featured),
    []
  );

  return {
    ideas: filteredAndSortedIdeas,
    featuredIdeas,
    filters,
    setFilters,
    sortBy,
    setSortBy,
    industries: INDUSTRIES,
    provinces: PROVINCES,
    totalCount: PRE_VALIDATED_IDEAS.length,
  };
};
